### PR TITLE
Localization fixed

### PR DESCRIPTION
**Pull request by Gedevan-Aleksizde**
* missing and mistaken localization IDs in XML files fixed
* missing and mistaken localization IDs in CS files fixed
* some trivial typos fixed
* translation template files added

I can't test whole the changes, but I assume there are no critical errors.

### CODE REVIEW

**Review by enisn — APPROVED** [review]
Perfectly done, I came here to make these changes and I saw you already done👏

**Comment by enisn** [comment]
@R-Vaccari what do you think about this PR?

It's highly required for other language translations

**Comment by GF-Huang** [comment]
The source code seems merged the changes, but why not merge this PR directly?

**Comment by R-Vaccari** [comment]
Banner Kings uses a separate small program to generate localization keys as of provided by a contributor. These changes were not merged nor are any changes of this type required to be contributed. I than the original author for his willingness to help.

**Comment by GF-Huang** [comment]
@R-Vaccari Thank you for creating this great mod. But it doesn't seem to be perfect in terms of translation at the moment, there are still a lot of strings that don't have localization keys, what should I do to improve it? What is the correct approach?

**Comment by R-Vaccari** [comment]
@GF-Huang I suppose there is a way to contribute. When I started the mod I didnt understand localization and we certainly didnt have the program to generate the keys. If you find any hardcoded strings or text objects, you can help by adding ` {=!} ` to it. In a old mod texts you might find `new TextObject("Text Here")` or just plain `"Text Here"`. The correct approach is to leave it as `new TextObject("{=!}Text Here")`. In this way the localizer program will pick this string up when I run it, and generate a key.

**Comment by enisn** [comment]
There are a lot of unlocalized texts (`{=!}Text Here"`), can you run that localizer program and update the mod by yourself?

**Comment by R-Vaccari** [comment]
@GF-Huang its just a system variable pointing to Bannerlords steam installation.
@enisn please reread my comment.

**Comment by GF-Huang** [comment]
@R-Vaccari Should the **Path to Modules folder** be "**Mount & Blade II Bannerlord\Modules\BannerKings**" or "**Mount & Blade II Bannerlord\Modules**"?

image

**Comment by GF-Huang** [comment]
Another serious problem I found is that there are currently a lot of different texts using the same ID. Is this really okay?

image

<details>
<summary>Duplicates</summary>
<code>
Text ID conflict: dugq4xHo, "Grant {TITLE}" != "Grant"
Text ID conflict: 6hY9WysN, "Claimants" != "Claim"
Text ID conflict: SaWHeTiw, "Supplies such as alcohol and wood for firewood are required to preserve your retinue in good mental condition." != "Supplies"
Text ID conflict: SaWHeTiw, "Supplies are required to preserve your retinue in maximum efficiency. Your quartermaster is able to handle supplies if you instruct them directly." != "Supplies"
Text ID conflict: J6oPqQmt, "Settlement Effects" != "Settlement"
Text ID conflict: ueWn5rM4, "Alliance Offering" != "Alliance"
Text ID conflict: f8XaH0NC, "Archers have strong ranged skills focused on Bows, while maintaining decent speed and ability to defend themselves in close quarters." != "Archer"
Text ID conflict: f8XaH0NC, "Archers have strong ranged skills focused on Bows, while maintaining decent speed and ability to defend themselves in close quarters." != "Archer"
Text ID conflict: eQbfxno4, "The {WORKSHOP} has been seized from the {OWNER} at {TOWN} due to war between your realms. {TOWNOWNER} has gifted you this property." != "The {WORKSHOP} has been seized from the {OWNER} at {TOWN} due to war between your realms."
Text ID conflict: eQbfxno4, "The {WORKSHOP} has been seized from the {OWNER} at {TOWN} due to war between your realms. {TOWNOWNER} has gifted you this property." != "The {WORKSHOP} has been seized from the {OWNER} at {TOWN} due to war between your realms."
Text ID conflict: JqLT9Fro, "Traditionalists support the way of the ancestors. More than anything, they believe in strength. While they recognize the necessity for a strong ruler, they also do the necessity of liberty for the noble classes. They aim for a balance of power between the sovereign and their vassals, a continuation of old traditions and exerting power through force." != "Traditionalists"
Text ID conflict: ZhZFKHhO, "Oligarchists are noble people of influence that are concerned, first and foremost, with their own advantage. They continuously seek benefits for themselves or their peers, understanding they are part of the same class. Thus, their interests are often misaligned both with the ruler's, and with the common people." != "Oligarchists"
Text ID conflict: 3Yy4bGJj, "Zealots represent those of most religious fervor within the realm. As a group, they are most concerned with the strengthening of their faith and the upholding of its values. A ruler that does not follow the realm's traditional faith will have great difficulty gathering support from such zealots. Those that do follow it, still need to prove themselves by upholding the faith's virtues. Zealots, loyal first and foremost to their faith, gather members both within and withou the nobility." != "Zealots"
Text ID conflict: kyB8tkgY, "Commoners represent the general populace, intermediated by fief dignataries. The benefit of the commoners often clashes with the benefit of the high nobility. However, the populace is open to supporting rulers that represent them. Often, that means a shared cultural and religious tradition, as well as signs of certain virtues, such as a keen sense of justice and generosity." != "Commoners"
Text ID conflict: kyB8tkgY, "Conquer a fief" != "Commoners"
Text ID conflict: kyB8tkgY, "Cultural Liberation" != "Commoners"
Text ID conflict: kyB8tkgY, "Conquer the target fief" != "Commoners"
Text ID conflict: kyB8tkgY, "Claim Fief" != "Commoners"
Text ID conflict: kyB8tkgY, "Conquer a fief claimed by your realm. The benefactor of the conquest will always be the claimant, regardless of other ownership procedures.\n\nObjective: Capture the selected target." != "Commoners"
Text ID conflict: kyB8tkgY, "Conquer the target fief" != "Commoners"
Text ID conflict: kyB8tkgY, "Conquer Fiefs" != "Commoners"
Text ID conflict: kyB8tkgY, "Conquer 2 fiefs" != "Commoners"
Text ID conflict: kyB8tkgY, "Conquer Fiefs" != "Commoners"
Text ID conflict: kyB8tkgY, "Concede" != "Commoners"
Text ID conflict: RYmV2PEY, "Demand that the ruler assume the legal faith of the realm." != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: kyB8tkgY, "Council Position" != "Commoners"
Text ID conflict: kyB8tkgY, "Concede" != "Commoners"
Text ID conflict: RYmV2PEY, "Deny the demand to put {BENEFACTOR} in charge of the {POSITION} position. They will not like this outcome." != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: kyB8tkgY, "Choose the benefactor for the {POSITION} position." != "Commoners"
Text ID conflict: kyB8tkgY, "Cast your vote on who should be the benefactor for the {POSITION} position." != "Commoners"
Text ID conflict: RYmV2PEY, "Dispute (Lordship)" != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: RYmV2PEY, "Dispute on legal terms the efficacy of this demand. {LEADER} may or not be compelled to conceded, based on their Lordship ({LEADER_LORDSHIP}) against yours ({PLAYER_LORDSHIP}). Whether the group is satisfied or not depends on the leader being convinced.\nMinimum Lordship: {LORDSHIP}" != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: RYmV2PEY, "Demesne Law Change" != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: RYmV2PEY, "Demand a change to one of the existing demesne laws. An Interest Group may demand that a law is changed to one of the variants of said law that the group supports. For more information on laws, read the Demesne Laws on encyclopedia." != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: kyB8tkgY, "Concede" != "Commoners"
Text ID conflict: RYmV2PEY, "Deny the demand to pass the {LAW} law. They will not like this outcome." != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: RYmV2PEY, "Dispute (Lordship)" != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: RYmV2PEY, "Dispute on legal terms the efficacy of this demand. {LEADER} may or not be compelled to conceded, based on their Lordship ({LEADER_LORDSHIP}) against yours ({PLAYER_LORDSHIP}). Whether the group is satisfied or not depends on the leader being convinced.\nMinimum Lordship: {LORDSHIP}" != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: kyB8tkgY, "Choose the benefactor for the {POSITION} position." != "Commoners"
Text ID conflict: kyB8tkgY, "Concede" != "Commoners"
Text ID conflict: RYmV2PEY, "Deny the demand to change the state of the {POLICY} policy. They will not like this outcome." != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: RYmV2PEY, "Dispute (Lordship)" != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: RYmV2PEY, "Dispute on legal terms the efficacy of this demand. {LEADER} may or not be compelled to conceded, based on their Lordship ({LEADER_LORDSHIP}) against yours ({PLAYER_LORDSHIP}). Whether the group is satisfied or not depends on the leader being convinced.\nMinimum Lordship: {LORDSHIP}" != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: kyB8tkgY, "Choose the benefactor for the {POSITION} position." != "Commoners"
Text ID conflict: kyB8tkgY, "Council Position" != "Commoners"
Text ID conflict: kyB8tkgY, "Concede" != "Commoners"
Text ID conflict: RYmV2PEY, "Deny the demand to grant {BENEFACTOR} the {TITLE} title. They will not like this outcome." != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: kyB8tkgY, "Choose the benefactor for the {TITLE} position." != "Commoners"
Text ID conflict: kyB8tkgY, "Cast your vote on who should be granted the {TITLE} title." != "Commoners"
Text ID conflict: oOTc2x9R, "Guilds are associations of artisans that concern a specific trade. Their main purpose was the regulate a specific craft, trainning artisans, guaranteeing a minimum level of quality and destroying forgeries. This would allow, for example, artisans of a specific town to be renowned in a given craft, driving prices up and thus the guild's profits. Yet, this source of power among the merchants and artisans may prove a source of conflict with their noble overlords." != "Guilds"
Text ID conflict: kyB8tkgY, "C" != "Commoners"
Text ID conflict: CCfPK6ew, "Wisdom represents your world knowledge and competence to deal with skills that require deep learning." != "Wisdom"
Text ID conflict: pjEnC3ur, "Attractiveness is how objectively likable one's physical appearance is. It is a trait inherited from one's parents. Attractive persons are naturally more Charmful and tend to have more children with their spouses.\nEffects:\nAdded Charm points\nIncreased fertility\nCharacters are more sexually attracted to you" != "Attractiveness"
Text ID conflict: NibmshX7, "Robustness describes one's physical resilience. It is a trait inherited from one's parents. Robust persons are said to have more Endurance and be harder to kill on the battlefield.\nEffects:\nAdded Endurance points\nIncreased character health" != "Robustness"
Text ID conflict: kyB8tkgY, "Construct a mill, used to grind grains for breadmaking. Increases bread production (50%, 100%, 150%)." != "Commoners"
Text ID conflict: UHyznyEy, "Manor house, the lord's home and center of the village. A manor house allows the housing of a small retinue in the village (15, 30, 45 men). Increases influence from nobles (15%, 30%, 50%)." != "Manor"
Text ID conflict: VCbuZK6B, "Hire a small amount of servants to operate mundane tasks such as cleaning or cooking within the court. Increases feast satisfaction and decreases defense against schemes the most." != "Hire a small amount of servants to operate mundane tasks such as cleaning or cooking within the court."
Text ID conflict: tRp08jyH, "Battanian settlements have +{EFFECT1} militia\nReduced damage by {EFFECT2}% when mounted" != "Battanian"
Text ID conflict: C8eDVQJw, "Levy Duty (1/2)" != "Levy Duty"
Text ID conflict: C8eDVQJw, "Levy Duty (2/2)" != "Levy Duty"
Text ID conflict: kyB8tkgY, "Commander" != "Commoners"
Text ID conflict: FVA72PZG, "Guests (2/2)" != "Guests (1/2)"
Text ID conflict: pKoKaKNd, "Sentence Criminal (1/2)" != "Sentence Criminal"
Text ID conflict: pKoKaKNd, "Sentence Criminal (2/2)" != "Sentence Criminal"
Text ID conflict: kyB8tkgY, "Calradoi Age" != "Commoners"
Text ID conflict: aGjvnUcL, "Ancestor Heroine" != "Ancestor Hero"
Text ID conflict: 1Vu06pAN, "Iltanlar is the god of a mountain-dwelling Devseg group, who migrated from the Sulun Dag mountain range to mount Iltan, and have since been assimilated by the eastern hordes of their cousins. The Iltanlar people value security above most things, thus they have for long dwelled in the mountains, which they perceive to be bountiful in good, protective spirits. Iltanlar, the god, is said to be an ancient hero, who guided his people to their new promised home, where since the Iltanlar people have founded Baltakhand." != "Iltanlar"
Text ID conflict: x6cAcipf, "Yel Uçmag, the God of Heaven, also known as the first wind. He is the guardian of Heaven, Uçmag, where the souls of the rightous dwell. For this he is the most hollowed of the Devseg deities, for he hosts the souls of their ancestors, who live in a world of perfect, uncorrupted nature and tradition. He is said to wear armor and weapons of silver, as pure as the heavenly realm he guards." != "Yel Uçmag"
Text ID conflict: vZF66o30, "Yel Kunmag is the god of the Solar Wind, or Southern Wind as the non-Devseg would call him. To these, the Land of the Sun lies in the south, where Yel Kunmag flows to. The Sun is an immensely powerful force in the Devseg cosmos, and as such Yel Kunmag is bestowed great influence. Yel Kunmag's investure is seen as a royal prerogative, for the Sun is capable of both raising and destroying Khaganates." != "Yel Kunmag"
Text ID conflict: nGXuvwvX, "Yel Togmag, or the Eastern Wind, is the Devseg Godess that presides over life. Tog, to be born, is her domain, life she bestows the Sun, daugther of Yel Uçmag. Many faithul, during their prayers, turn towards the East in her honor. The Devseg welcome the Eastern Wind as a blessing of fertility and prosperity - a good omen, by all standards." != "Yel Togmag"
Text ID conflict: 7ZzktggC, "Wilund is known to non-Vlandians as the first Vlandic warlord to come to the continent. Yet the Vlandic tales tell the story of not a mercenary warlord, but a celestial smith, whose foundry is the world. The stories of how kingdoms rise and fall - that is the craft of Wilund. As such, hestawicks will assure he came to Calradia to make way for the Vlandians to carve their kingdom, or perhaps, kingdoms..." != "Wilund"
Text ID conflict: 7ZzktggC, "Wilund is the celestial smith. The world is his foundry. The thunder of the storm and the thunder of hooves are the song of his hammer. The black rain of a thousand arrows of war are the sparks upon his anvil. When he tempers life, a thousand men die and a thousand more are born." != "Wilund"
Text ID conflict: oeFFK9Y8, "Oca, a god favored by the Swedaz, is often depicted as an Ox. He is believed to have the power to provide his faithful with bountiful crop yields, who were traditionally ploughed with oxen teams. Yet, it does not mean he is harmless, or to be trifled with - Oca may slaughter his enemies, including those that do not keep their oaths to him. His cult is strongest in eastern Vlandia, around Ocs Hall, named in his honor, but also a land of many legends." != "Oca"
Text ID conflict: RYmV2PEY, "D" != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: kyB8tkgY, "Cultural innovations develop faster (when Cultural Head)\nShip travels are faster" != "Commoners"
Text ID conflict: kyB8tkgY, "Combat is considered by the faith a pious practice. The gods decide the winner, and to attempt to escape our fate through cravenness is an offence to the gods." != "Commoners"
Text ID conflict: FRAS5TAC, "Woodland acreage provides piety\nReduced baseline fervor" != "Woodland"
Text ID conflict: MBYo3Pjx, "Schools" != "School"
Text ID conflict: MBYo3Pjx, "Schools" != "School"
Text ID conflict: 9N6T6kWF, "Alti Yel, or Six Winds, represents the Devseg beliefs that the universe is, in essence, an everflowing current. Six Winds represent the aspects of this current: U�mag, Tamag, Kurmag, Kunmag, Batmag, Togmag. Each of them is represented by a god or godess, who embodies a necessary aspect of the cosmos, such as the life or death. The Devseg hold all of them in high regard, but U�mag, Heaven, as the most important guide to their ethics, as every faithful strives to reach the purity of U�mag on their death. Besides the pantheon of gods, spirits are known to inhabit the natural world, specially mountains, streams and lakes. Such spirits can be benign or otherwise - only through the shamans, the Kams, can the Devseg communicate with and understand them. The Devseg also believe in the Great She-Wolf, who many a great house claims to be their ancestors. Sighting wolves is often considered a good omen, and to be considered a half-wolf is a great honor. Notably tolerant of other faiths, the Six Winds shamans have also incorporated the local Devseg beliefs of Iltanlar, a mountain god of a Devseg tribe that settled on Baltakhand long before the arrival of the hordes." != "Alti Yel, or Six Winds, represents the Devseg beliefs that the universe is, in essence, an everflowing current. Six Winds represent the aspects of this current: U�mag, Tamag, Kurmag, Kunmag, Batmag, Togmag. Each of them is represented by a god or godess, who embodies a necessary aspect of the cosmos, such as the life or death. The Devseg hold all of them in high regard, but U�mag, Heaven, as the most important guide to their ethics, as every faithful strives to reach the purity of U�mag on their death."
Text ID conflict: J4D4X2XJ, "Cults" != "Cult"
Text ID conflict: J4D4X2XJ, "Cults" != "Cult"
Text ID conflict: 6Yj8erp7, "May be performed every {YEARS} years\nRequires a weapon of type ({TYPE})" != "May be performed every {YEARS} years\nRequires {COUNT} {ITEM}"
Text ID conflict: neVhyybi, "Sagas" != "Saga"
Text ID conflict: 2rby15CO, "Are you sure? If so, you shall take these teachings deep into your heart. Let your soul sing for the anguished fallen, and hope one day you may join them in the Canticles!" != "Are you sure?"
Text ID conflict: kyB8tkgY, "Confirm to me your devotion, lest have your name forgotten." != "Commoners"
Text ID conflict: O6WGvv56, "Osfeyd, or 'faith in the gods' in the Vlandic tongue, is the combined beliefs brought by the various Vlandic peoples, woven together by the prophecy of Horsa, made true by Osric Iron-Arm. In search of new fertile farmland, the Wilunding have killed the Calradic gods in the west. Their gods make sure they are not but mere farmers - many a man have died, pierced by their lances and bolts, such that their kingdom may thrive. This is the tale of their mighty canticle." != "Osfeyd, or 'faith in the gods' in the Vlandic tongue, is the combined beliefs brought by the various Vlandic peoples, woven together by the prophecy of Horsa, made true by Osric Iron-Arm. In search of new fertile farmland, the Wilunding have killed the Calradic gods in the west."
Text ID conflict: ZNU4rSxp, "{?PLAYER.GENDER}My lady{?}My lord{\\?}, a feast for the Goddess would be a most pious choice. Let her ease the coming autumn and winter and bring us a bountiful spring." != "{?PLAYER.GENDER}My lady{?}My lord{\\?}, a blade sacrifice would certainly please the spirits, aye. A high quality is expected, so it may be worthy of your ancestors. Will you offer the {BLADE}?"
Text ID conflict: kyB8tkgY, "Contract Structure Change" != "Commoners"
Text ID conflict: RYmV2PEY, "Distributed Conquest" != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: kyB8tkgY, "Conquest by Claim" != "Commoners"
Text ID conflict: kyB8tkgY, "Conquest by Might" != "Commoners"
Text ID conflict: F72Gfcyg, "Agnatic gender law gives precedence to male inheritors over females. While females are not blocked from inheritance, it its likely they will only inherit after the male options are exhausted, unless a female can exceed quite significantly in competence the best existing male option. Females are suppressed from important positions such as knighthood." != "Agnatic"
Text ID conflict: kyB8tkgY, "Cognatic" != "Commoners"
Text ID conflict: kyB8tkgY, "Cognatic gender law gives no precedence to any of either genders, allowing both to fulfill important positions, and clan inheritances to be based solely on their competence criteria. For example, with Cognatic Primogeniture, the eldest child should inherit the clan, regardless of their gender." != "Commoners"
Text ID conflict: A4pJzFUm, "Enatic gender law gives precedence to female inheritors over males. While males are not blocked from inheritance, it its likely they will only inherit after the female options are exhausted, unless a male can exceed quite significantly in competence the best existing female option. Males are suppressed from important positions such as knighthood." != "Enatic"
Text ID conflict: bAzfVpGy, "Feudal governments stablish the authority of a life-serving ruler, while keeping a relatively degree of autonomy to their vassals. Unlike in empires, feudal societies have a strong sense of property, and legal claims and technicalities often take precedence over other factors. While the king or queen draw great influence, their subordinate peers are guaranteed certain securities that the ruler is bound by law to follow." != "Feudal"
Text ID conflict: 2VAxdqb0, "Primogeniture inheritance gives precedence to the children of the deceased, from eldest to youngest. Whether the firstborn son or daughter will be chosen depends on the Gender Law in place." != "Primogeniture"
Text ID conflict: zqkBqFJf, "Ultimogeniture inheritance gives precedence to the children of the deceased, from youngest to eldest. Whether the youngest son or daughter will be chosen depends on the Gender Law in place." != "Ultimogeniture"
Text ID conflict: HOoAoUV7, "Seniority inheritance gives no precedence to any particular member of a household. The main criteria is their age, meaning that household members without blood ties may take precedence over children or close relatives. Whether the eldest man or woman will be chosen depends on the Gender Law in place." != "Seniority"
Text ID conflict: 7GEoJHN8, "Nahawasi Elective" != "Nahawasi"
Text ID conflict: RYmV2PEY, "Dictatorship" != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: SW29YLBZ, "Imperial" != "Imperial Cult"
Text ID conflict: 7FEVXuj2, "Tribal Elective" != "Tribal"
Text ID conflict: 7FEVXuj2, "Tribal Elective succession describes a generalized form of succession for the non-feudal and non-imperial cultures of Calradia. Such practices often care little for dynastic inheritance and none for legal trivialities such as claims. Instead, strong competent leaders are respected, specially those with renowned names, for these are the types of rulers that can rally together rivaling tribes that would otherwise be destroying each other." != "Tribal"
Text ID conflict: 7ZzktggC, "Wilunding Elective" != "Wilund"
Text ID conflict: kyB8tkgY, "Court location ({NAME})" != "Commoners"
Text ID conflict: kyB8tkgY, "Current Income" != "Commoners"
Text ID conflict: kyB8tkgY, "Castles (x{COUNT})" != "Commoners"
Text ID conflict: kyB8tkgY, "Culture match with {KINGDOM}" != "Commoners"
Text ID conflict: kyB8tkgY, "Clan Influence Limit" != "Commoners"
Text ID conflict: kyB8tkgY, "Clan Influence Limit" != "Commoners"
Text ID conflict: 7x3HJ29f, "Kingdom can be founded." != "Kingdom"
Text ID conflict: GMOKktYa, "Defender's perspective" != "Defender"
Text ID conflict: pA8rNnUH, "Raid" != "Raiding and pillaging is understood as a pious practice. This faith"
Text ID conflict: OdpuFusm, "Encourage mercantilism decision" != "Encourage mercantilism"
Text ID conflict: kyB8tkgY, "Castle" != "Commoners"
Text ID conflict: fTKqtNxB, "Learning Limit Exceeded" != "Learning Limit"
Text ID conflict: NeydSXjc, "Score differences" != "Score"
Text ID conflict: zyKSROjQ, "Kingdoms" != "King"
Text ID conflict: QCw05MZN, "Household" != "Household members heal faster in settlements\nDaily medicine xp for household members"
Text ID conflict: FVA72PZG, "Guests" != "Guests (1/2)"
Text ID conflict: 4aKx5Pj9, "Materials" != "Material"
Text ID conflict: J6oPqQmt, "Settlements:" != "Settlement"
Text ID conflict: kyB8tkgY, "Change Fascination" != "Commoners"
Text ID conflict: kyB8tkgY, "Choose Research" != "Commoners"
Text ID conflict: kyB8tkgY, "Choose a research proejct. Your current research progress is {PROGRESS} research points, based on your Scholarship, Intelligence and perks. An innovation is researchable if it has no previous requirements or its direct requirement is already fully researched.{newline}{newline}To make progress in your research, visit a friendly fief, select Banner Kings -> Take an Action -> Research." != "Commoners"
Text ID conflict: J6oPqQmt, "Settlements:" != "Settlement"
Text ID conflict: NvnA9WyM, "Books Read" != "Books"
Text ID conflict: NvnA9WyM, "Books need to be in your inventory or the current settlement's Stash in order to be readable. To start reading you need to be literate and either have a dictionary or have a minimum understanding of it's language." != "Books"
Text ID conflict: NvnA9WyM, "Books need to be in your inventory or the current settlement's Stash in order to be readable. To start reading you need to be literate and either have a dictionary or have a minimum understanding of it's language." != "Books"
Text ID conflict: o1Z28eXv, "Name:" != "Name"
Text ID conflict: KBsVXEtH, "Languages may be taught by your courtiers that have a good fluency, so long they understand it more than you. Languages can be actively studied on the settlement the courtier is located at." != "Languages"
Text ID conflict: o1Z28eXv, "Name:" != "Name"
Text ID conflict: KBsVXEtH, "Languages limit:" != "Languages"
Text ID conflict: KBsVXEtH, "Languages may be taught by your courtiers that have a good fluency, so long they understand it more than you. Languages can be actively studied on the settlement the courtier is located at." != "Languages"
Text ID conflict: kyB8tkgY, "Consider proposing a diplomatic action" != "Commoners"
Text ID conflict: EDyKXsvE, "Successions determine how the realm rulership is passed on the death or end of term of the current ruler. You may propose a change to the succession process that will be voted on by the peers.{newline}{newline}For more information, search for Successions in Encyclopedia." != "Successions"
Text ID conflict: t9N3L0Oy, "Inheritances determine how clan leadership and properties are passed on the death of the clan head. You may propose a change to the inheritance process that will be voted on by the peers.{newline}{newline}For more information, search for Inheritances in Encyclopedia." != "Inheritances"
Text ID conflict: kyB8tkgY, "Contract Structure" != "Commoners"
Text ID conflict: 91WqQDR9, "Research:" != "Research"
Text ID conflict: ZYyxmOv9, "Request" != "Request to swap your current position with {COUNCILMAN} position of {POSITION}. This action will cost {INFLUENCE}{INFLUENCE_ICON}."
Text ID conflict: kyB8tkgY, "Career Points" != "Commoners"
Text ID conflict: kyB8tkgY, "Create" != "Commoners"
Text ID conflict: kyB8tkgY, "Create" != "Commoners"
Text ID conflict: kyB8tkgY, "Custom Levy" != "Commoners"
Text ID conflict: kyB8tkgY, "Create a custom levy troop! This troop will be available in towns of {CULTURE} culture. They will only be available for your clan, and can be retrained or rearmed on demand - though these will incur costs. Their recruitment and upkeep costs will depend on the equipment you give them. First, give them a name." != "Commoners"
Text ID conflict: kyB8tkgY, "Custom Professional" != "Commoners"
Text ID conflict: kyB8tkgY, "Create a custom professional troop! This troop will be available in towns of {CULTURE} culture. They will only be available for your clan, and can be retrained or rearmed on demand - though these will incur costs. Their recruitment and upkeep costs will depend on the equipment you give them. First, give them a name." != "Commoners"
Text ID conflict: kyB8tkgY, "Clear all equipments" != "Commoners"
Text ID conflict: we2yiKUb, "Edit the {TROOP} to better fit your needs." != "Edit"
Text ID conflict: kyB8tkgY, "Choose a skill set that fits the function you want to give your troops, from melee infantry to mounted skirmishers. Equipment is edited separately, make sure to choose skills that match their equipment." != "Commoners"
Text ID conflict: we2yiKUb, "Edit Name" != "Edit"
Text ID conflict: kyB8tkgY, "Change the name of {TROOP}." != "Commoners"
Text ID conflict: kyB8tkgY, "Choose the item selection for this equipment slot. You may choose from 1 to 5 items." != "Commoners"
Text ID conflict: OKw2P9m1, "Faith Group" != "Faith"
Text ID conflict: OKw2P9m1, "Faith Group" != "Faith"
Text ID conflict: mUaJDjqO, "Council" != "Council member for position {POSITION}"
Text ID conflict: OKw2P9m1, "Faith:" != "Faith"
Text ID conflict: AaS8WTzj, "Personal decisions affect your character and sometimes your close family." != "Personal"
Text ID conflict: AaS8WTzj, "Personal decisions affect your character and sometimes your close family." != "Personal"
Text ID conflict: 8uURr54W, "Religious decisions are ways for you interact with the world through your faith." != "Religious"
Text ID conflict: 8uURr54W, "Religious decisions are ways for you interact with the world through your faith." != "Religious"
Text ID conflict: kyB8tkgY, "Criminal" != "Commoners"
Text ID conflict: kyB8tkgY, "Criminal decisions relate to carrying out sentences or crimes. Captured criminals can be sentenced with a criminal decision." != "Commoners"
Text ID conflict: kyB8tkgY, "Criminal" != "Commoners"
Text ID conflict: kyB8tkgY, "Criminal decisions relate to carrying out sentences or crimes. Captured criminals can be sentenced with a criminal decision." != "Commoners"
Text ID conflict: 8MLr4eSD, "Unique decisions are difficult and special decisions that often can only be taken once, such as reviving a historical empire." != "Unique"
Text ID conflict: 8MLr4eSD, "Unique decisions are special decisions that often can only be taken once, such as reviving a historical empire." != "Unique"
Text ID conflict: RYmV2PEY, "Drafting increases the military participation of your estate population, but reduces its general output." != "Deny the demand to assumne the {RELIGION} faith. They will not like this outcome."
Text ID conflict: HojX6KBq, "Acre Value represents the monetary value of each acre, variable according to the local economy." != "Acre Value"
Text ID conflict: OXrRc2H1, "Estate Value is the estate's monetary price, according to its acreage, income and local economy." != "Estate Value"
</code>
</details>

**Pull request closed without merging**
